services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 6500:5432
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: